#!/bin/sh

echo "Xft.dpi: 144" | xrdb -merge
bspc monitor DP3 -d I II III IV V VI
bspc monitor DP1 -d VII VIII
bspc monitor eDP1 -d IX X
bspc wm -O DP3 DP1 eDP1
~/.config/polybar/launch.sh
~/.fehbg &
