#!/bin/bash

set -e

BUILDDIR="${BUILDDIR:-/tmp/buildd}"

apt-get install -y "${APTGETOPT[@]}" lintian

echo "+++ lintian output +++"

su -c "lintian -iIEcv --pedantic --color auto --show-overrides "$BUILDDIR"/*.changes" - pbuilder
# use this version if you don't want lintian to fail the build
#su -c "lintian -I --show-overrides "$BUILDDIR"/*.changes; :" - pbuilder

echo "+++ end of lintian output +++"
