#!/bin/sh

# Determine XrandR settings
if [[ "$(xrandr | grep -c -w 'DP1 connected\|DP3 connected')" -eq 2 ]]; then
  # Docked mode
  echo "Xft.dpi: 144" | xrdb -merge
  xrandr --output eDP1 --off \
    --output DP3 --primary --mode 3840x2160 --pos 0x0 \
    --output DP1 --mode 1600x1200 --pos 3840x0
else
  # Mobile mode
  xrandr --output eDP1 --primary --mode 3840x2160 --pos 0x0 \
    --output DP3 --off \
    --output DP1 --off
  echo "Xft.dpi: 192" | xrdb -merge
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Define desktop[s] [per monitor]
if [ "$(xrdb -query | awk '/dpi/ {print $2}')" -eq 144 ]; then
  bspc monitor DP3 -d " I" II III IV V VI VII VIII
  bspc monitor DP1 -d  
else
  bspc monitor eDP1 -d " I" II III IV V VI VII VIII  
fi

# Border and Gap
bspc config border_width         5
bspc config window_gap          10

# Configuration
bspc config split_ratio          0.50

# Mouse
bspc config click_to_focus	 	button1
bspc config focus_follows_pointer 	true

# Monocle mode settings
bspc config borderless_monocle   false
bspc config gapless_monocle      true

# Colors
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#ebcb8b"

# Launch sxhkd
sxhkd &

# Launch libinput-gestures
libinput-gestures &

# Set the cursor
xsetroot -cursor_name left_ptr

# Launch redshift with coordinates of where I am
redshift &

# Launch notification server
dunst &

# Launch authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Autohide the cursor when inactive
unclutter --ignore-scrolling &

# Launch polybar
~/.config/polybar/launch.sh

# Set the desktop background
~/.fehbg &

# Call the compositor
picom &

# Disable USB auto-suspend for mouse and keyboard
sudo powertop-fix.sh

# Lock the screen
lock.sh
