#!/bin/sh

mode=''
EXTERNAL_OUTPUT_1="DP3"
EXTERNAL_OUTPUT_2="DP1"
INTERNAL_OUTPUT="eDP1"

help() {
  printf "desktop-mode: \n\t\t -1 to turn on\n\t\t -0 to turn off\n"
  exit 1
}

on() {
  xrandr --output $INTERNAL_OUTPUT --off --output $EXTERNAL_OUTPUT_1 --auto --output $EXTERNAL_OUTPUT_2 --auto --right-of $EXTERNAL_OUTPUT_1
  setxkbmap -option compose:rctrl -option lv3:ralt_switch -option eurosign:5 -option rupeesign:4
}

off() {
  xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT_1 --off --output $EXTERNAL_OUTPUT_2 --off
}

while getopts '01h' flag; do
  case "${flag}" in
    0) mode='false' ;;
    1) mode='true' ;;
    h) help ;;
  esac
done

if [ "$mode" = true ]; then
  on
elif [ "$mode" = false ]; then
  off
else
  help
fi

i3-msg restart
notify-send 'Desktop mode: '$mode --icon=computer
